# Default values for basic-tme-transformer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "basic-tme-transformer" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/basic-tme-transformer
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 800Mi
  limits:
    memory: 1.5Gi
cache:
  size: 5Gi
  path: "/"
env:
  BASE_URL: "http://basic-tme-transformer:8080/transformers"
  CACHE_FILE_NAME: "/cache/basic-tme-transformer.db"
  LOG_METRICS: "false"
  WRITER_ENDPOINT: "http://concepts-rw-s3:8080/concepts"
  WRITER_WORKERS: "10"
