version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/basic-tme-transformer
    docker:
      - image: golang:1.10
        environment:
          CIRCLE_TEST_REPORTS: /tmp/test-reports
          CIRCLE_ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - run:
          name: Create folders
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/golang
            mkdir -p $CIRCLE_ARTIFACTS
      - run:
          name: External Dependancies
          command: |
            go get -u github.com/mattn/goveralls
            go get -u github.com/golang/dep/cmd/dep
            go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Download vendored dependancies
          command: |
            dep ensure
      - run:
          name: Go Build
          command: |
            go build -v
      - run:
          name: Run tests and create coverage report
          command: |
            go test ./... -v -race -cover -coverprofile=$CIRCLE_ARTIFACTS/coverage.out | go-junit-report > $CIRCLE_TEST_REPORTS/golang/junit.xml
            sed -i "/_mock/d" ${CIRCLE_ARTIFACTS}/coverage.out
      - run:
          name: Upload coverage report
          command: |
            goveralls -coverprofile=$CIRCLE_ARTIFACTS/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-reports
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
  dockerfile:
    working_directory: /basic-tme-transformer
    docker:
      - image: docker:18.03
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .