kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.service.name }}-cache-pvc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.cache.size }}
  selector:
    matchLabels:
      provisioned-for: "{{.Values.service.name}}"
